import { DomHashComparisonResult } from './index';
import pkg from '../../package.json';

/**
 * Generates an HTML representation of the DOM hash comparison results.
 *
 * This function takes a `DomHashComparisonResult` object and formats it into a 
 * well-structured HTML document. The resulting HTML includes details such as 
 * SHA hashes, structural similarity percentages, and any structural differences 
 * found between two DOM representations. It is useful for visually presenting 
 * the comparison results in a web browser.
 *
 * @param result - An object containing the results of the DOM hash comparison.
 *                 It should include the following properties:
 *                 - `hashA`: The SHA hash of the first DOM representation.
 *                 - `hashB`: The SHA hash of the second DOM representation.
 *                 - `similarity`: A number representing the structural similarity 
 *                   between the two DOMs (0 to 1).
 *                 - `shapeSimilarity`: (Optional) A number representing the shape 
 *                   similarity between the two DOMs (0 to 1).
 *                 - `diff`: An array of strings representing the structural 
 *                   differences, where lines starting with '+' indicate additions 
 *                   and lines starting with '-' indicate deletions.
 * @returns A string containing the complete HTML markup for displaying the 
 *          DOM hash comparison results.
 *
 * @example
 * ```typescript
 * const result: DomHashComparisonResult = {
 *   hashA: 'abc123',
 *   hashB: 'def456',
 *   similarity: 0.95,
 *   shapeSimilarity: 0.85,
 *   diff: ['+ New element', '- Removed element']
 * };
 * const htmlOutput = formatAsHTML(result);
 * console.log(htmlOutput); // Outputs the generated HTML string
 * ```
 */
export function formatAsHTML(result: DomHashComparisonResult): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>DOM Hash Comparison</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 2em; background: #f9f9f9; color: #222; }
    h2 { border-bottom: 2px solid #ccc; padding-bottom: 0.2em; }
    .version { font-size: 0.9em; color: #666; margin-top: -1em; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 2em; }
    th, td { padding: 0.5em 1em; border-bottom: 1px solid #ddd; text-align: left; }
    code { background: #eee; padding: 0.2em 0.4em; border-radius: 4px; }
    pre { background: #333; color: #f8f8f2; padding: 1em; overflow-x: auto; border-radius: 5px; }
    .add { color: #0c0; }
    .del { color: #c00; }
    .footer { margin-top: 2em; font-size: 0.9em; color: #777; }
  </style>
</head>
<body>
  <h2>DOM Hash Comparison</h2>
  <div class="version">Version: ${pkg.version}</div>
  <table>
    <tr><th>SHA A</th><td><code>${result.hashA}</code></td></tr>
    <tr><th>SHA B</th><td><code>${result.hashB}</code></td></tr>
    <tr><th>Structural Similarity</th><td>${(result.similarity * 100).toFixed(2)}%</td></tr>
    ${result.shapeSimilarity != null ? `<tr><th>Shape Similarity</th><td>${(result.shapeSimilarity * 100).toFixed(2)}%</td></tr>` : ''}
  </table>
  ${result.diff?.length ? `<h3>Structural Diff</h3><pre><code>${result.diff.map(line => {
    if (line.startsWith('+')) return `<span class='add'>${line}</span>`;
    if (line.startsWith('-')) return `<span class='del'>${line}</span>`;
    return line;
  }).join('\n')}</code></pre>` : ''}
  <div class="footer">
    Generated by <a href="https://www.npmjs.com/package/@iocium/domhash">@iocium/domhash</a><br>
    <em>Disclaimer: Similarity and resilience scores are heuristic and may not reflect all visual or behavioral aspects of a web page.</em>
  </div>
</body>
</html>`;
}