import { DomHashComparisonResult } from './index';
import pkg from '../../package.json';

/**
 * Formats the DOM hash comparison results into a Markdown string.
 *
 * This function generates a structured Markdown report based on the provided 
 * `DomHashComparisonResult`. The report includes details such as SHA hashes, 
 * structural similarity, shape similarity (if available), and any structural 
 * differences between the two DOM representations. This Markdown format is 
 * useful for documentation purposes, reporting, or sharing results in a readable 
 * format.
 *
 * @param result - An object containing the results of the DOM hash comparison.
 *                 It should include the following properties:
 *                 - `hashA`: The SHA hash of the first DOM representation.
 *                 - `hashB`: The SHA hash of the second DOM representation.
 *                 - `similarity`: A number representing the structural similarity 
 *                   between the two DOMs (0 to 1).
 *                 - `shapeSimilarity`: (Optional) A number representing the shape 
 *                   similarity between the two DOMs (0 to 1).
 *                 - `diff`: An array of strings representing the structural 
 *                   differences, where lines starting with '+' indicate additions 
 *                   and lines starting with '-' indicate deletions.
 * @returns A string containing the Markdown representation of the DOM hash 
 *          comparison results, formatted for readability and structured output.
 *
 * @example
 * ```typescript
 * const result: DomHashComparisonResult = {
 *   hashA: 'abc123',
 *   hashB: 'def456',
 *   similarity: 0.95,
 *   shapeSimilarity: 0.85,
 *   diff: ['+ New element', '- Removed element']
 * };
 * const markdownOutput = formatAsMarkdown(result);
 * console.log(markdownOutput); // Outputs the generated Markdown string
 * ```
 */
export function formatAsMarkdown(result: DomHashComparisonResult): string {
  const lines = [
    `### DOM Hash Comparison Report`,
    `\n_Version: ${pkg.version}_`,
    `\n**SHA A:** \`${result.hashA}\``,
    `**SHA B:** \`${result.hashB}\``,
    `**Structural Similarity:** \`${(result.similarity * 100).toFixed(2)}%\``
  ];

  if (result.shapeSimilarity != null) {
    lines.push(`**Shape Similarity:** \`${(result.shapeSimilarity * 100).toFixed(2)}%\``);
  }

  if (result.diff?.length) {
    lines.push(`\n**Structural Diff:**\n`);
    lines.push('```diff');
    lines.push(...result.diff);
    lines.push('```');
  }

  lines.push(
    `\n---`,
    `Generated by [@iocium/domhash](https://www.npmjs.com/package/@iocium/domhash)`,
    `_Disclaimer: Similarity and resilience scores are heuristic and may not reflect all visual or behavioral aspects of a web page._`
  );

  return lines.join('\n');
}